SELECT BG.NAME, Count_Belgian_IP
FROM GCD_BRAND_GROUP BG, (
    SELECT BG.ID AS BG_ID, COUNT(*) AS Count_Belgian_IP
    FROM GCD_INDICIA_PUBLISHER IP, STDDATA_COUNTRY C, GCD_BRAND_GROUP BG
    WHERE IP.COUNTRY_ID=C.ID AND C.NAME='Belgium' AND BG.PUBLISHER_ID=IP.PUBLISHER_ID
    GROUP BY BG.ID
) 
WHERE BG.ID=BG_ID AND Count_Belgian_IP=(SELECT MAX(Count_Belgian_IP) FROM (
    SELECT BG.ID AS BG_ID, COUNT(*) AS Count_Belgian_IP
    FROM GCD_INDICIA_PUBLISHER IP, STDDATA_COUNTRY C, GCD_BRAND_GROUP BG
    WHERE IP.COUNTRY_ID=C.ID AND C.NAME='Belgium' AND BG.PUBLISHER_ID=IP.PUBLISHER_ID
    GROUP BY BG.ID
    )
);