load data 
CHARACTERSET UTF8
into table GCD_SERIES
insert 
fields terminated by "|"
TRAILING NULLCOLS
(
    ID,
    NAME,
    FORMAT,
    YEAR_BEGAN,
    YEAR_ENDED,
    PUBLICATION_DATES,
    FIRST_ISSUE_ID,
    LAST_ISSUE_ID,
    PUBLISHER_ID,
    COUNTRY_ID,
    LANGUAGE_ID,
    NOTES char(4000),
    COLOR,
    DIMENSIONS,
    PAPER_STOCK,
    BINDING,
    PUBLICATION_TYPE_ID
)