SELECT DISTINCT S.FEATURE
FROM GCD_STORY S, GCD_ISSUE I, (
    SELECT ID, NAME
    FROM GCD_INDICIA_PUBLISHER
    WHERE LOWER(NAME) LIKE '%marvel%' AND LOWER(NAME) NOT LIKE '%dc%'
) Marvel_IP
WHERE (S.ISSUE_ID = I.ID) AND (I.INDICIA_PUBLISHER_ID = Marvel_IP.ID) AND S.FEATURE IS NOT NULL

INTERSECT

SELECT DISTINCT S.FEATURE
FROM GCD_STORY S, GCD_ISSUE I, (
    SELECT ID, NAME
    FROM GCD_INDICIA_PUBLISHER
    WHERE LOWER(NAME) LIKE '%marvel%' AND LOWER(NAME) LIKE '%dc%'
) Marvel_DC_IP
WHERE (S.ISSUE_ID = I.ID) AND (I.INDICIA_PUBLISHER_ID = Marvel_DC_IP.ID) AND S.FEATURE IS NOT NULL;