SELECT I.ID AS Issue_ID, ORIGIN_ID AS Story_ID, Count
FROM GCD_ISSUE I, (
    SELECT ORIGIN_ID, COUNT(DISTINCT TARGET_ID) AS Count
    FROM GCD_STORY_REPRINT
    GROUP BY ORIGIN_ID
    ORDER BY Count DESC
) Reprint_count
WHERE (ROWNUM <= 5) and (Reprint_count.ORIGIN_ID = I.ID);