SELECT S.FEATURE, Marvel_IP.NAME
FROM GCD_STORY S, GCD_ISSUE I, (
    SELECT ID, NAME
    FROM GCD_INDICIA_PUBLISHER
    WHERE LOWER(NAME) LIKE '%marvel%' 
) Marvel_IP
WHERE (S.ISSUE_ID = I.ID) AND (I.INDICIA_PUBLISHER_ID = Marvel_IP.ID);