SELECT IP.NAME AS Indicia_Publisher_Name, Count_Issue
FROM GCD_INDICIA_PUBLISHER IP, (
    SELECT INDICIA_PUBLISHER_ID, SERIES_ID, COUNT(*) AS Count_Issue
    FROM GCD_ISSUE
    GROUP BY INDICIA_PUBLISHER_ID, SERIES_ID
)
WHERE Count_Issue>=400 AND IP.ID=INDICIA_PUBLISHER_ID
ORDER BY Count_Issue DESC;