SELECT COUNT(*) AS Count_Per_year, Year_Date
FROM(
    SELECT EXTRACT(
        YEAR 
        FROM TO_DATE(PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR, 'MONTH YYYY')
    ) AS Year_Date
    FROM GCD_ISSUE
)
WHERE Year_Date>=1965 AND Year_Date<=1975
GROUP BY Year_Date
ORDER BY Year_Date;