SELECT P.NAME, Series_Count
FROM GCD_PUBLISHER P, (
    SELECT PUBLISHER_ID, COUNT(DISTINCT ID) AS Series_Count
    FROM GCD_SERIES
    GROUP BY PUBLISHER_ID
)
WHERE Series_Count>500 AND P.ID=PUBLISHER_ID
ORDER BY Series_Count DESC;
