SELECT COUNT_1 AS COUNT_DD_MM_YYYY, COUNT_2 AS COUNT_MM_DD_YYYY, COUNT_3 AS COUNT_MONTH_YYYY
FROM (
    SELECT COUNT(PUBLICATION_DATE) AS COUNT_1
    FROM (
        SELECT TO_DATE(PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR, 'DD/MM/YYYY')
            AS PUBLICATION_DATE
        FROM GCD_ISSUE
    )
),
(
    SELECT COUNT(PUBLICATION_DATE) AS COUNT_2
    FROM (
        SELECT TO_DATE(PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR, 'MM/DD/YYYY')
            AS PUBLICATION_DATE
        FROM GCD_ISSUE
    )
),
(
    SELECT COUNT(PUBLICATION_DATE) AS COUNT_3
    FROM (
        SELECT TO_DATE(PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR, 'MONTH YYYY')
            AS PUBLICATION_DATE
        FROM GCD_ISSUE
    )
);