SELECT IP.NAME, COUNT 
FROM GCD_INDICIA_PUBLISHER IP, (
    SELECT INDICIA_PUBLISHER_ID, SERIES_ID, COUNT(*) AS Count
    FROM GCD_ISSUE
    GROUP BY INDICIA_PUBLISHER_ID, SERIES_ID
)
WHERE Count>=400 AND IP.ID=INDICIA_PUBLISHER_ID
ORDER BY Count DESC;