SELECT NAME, COUNT 
FROM GCD_BRAND_GROUP BG, (
    SELECT BG.ID, COUNT(DISTINCT IP.ID) AS Count
    FROM GCD_BRAND_GROUP BG, GCD_INDICIA_PUBLISHER IP
    WHERE BG.PUBLISHER_ID=IP.PUBLISHER_ID
    GROUP BY BG.ID
) ID_COUNT
WHERE BG.ID=ID_COUNT.ID AND ID_COUNT.COUNT>100;