SELECT IP.NAME AS Indicia_Publisher_Name, count2 
FROM GCD_INDICIA_PUBLISHER IP ,(
    SELECT IP.ID, COUNT(*) count2
    FROM GCD_INDICIA_PUBLISHER IP, (
        SELECT INDICIA_PUBLISHER_ID, SERIES_ID, COUNT(*) AS count1
        FROM GCD_ISSUE
        GROUP BY INDICIA_PUBLISHER_ID, SERIES_ID
    )
    WHERE count1 = 1 AND IP.ID = INDICIA_PUBLISHER_ID
    GROUP BY IP.ID
) Single_Issue
WHERE count2>=400 AND Single_Issue.ID=IP.ID
ORDER BY Count2 DESC;