SELECT P.NAME AS Publisher_Name, Series_Language_Count
FROM GCD_PUBLISHER P, (
    SELECT PUBLISHER_ID, COUNT(DISTINCT LANGUAGE_ID) AS Series_Language_Count
    FROM (
        SELECT PUBLISHER_ID, LANGUAGE_ID FROM GCD_SERIES
        WHERE PUBLISHER_ID IN (
            SELECT ID 
            FROM (SELECT ID FROM GCD_PUBLISHER ORDER BY YEAR_BEGAN)
            WHERE ROWNUM <= 10
        )
    )
    GROUP BY PUBLISHER_ID
)
WHERE P.ID=PUBLISHER_ID;