SELECT DISTINCT PUBLICATION_DATE
FROM (
    SELECT EXTRACT(
        YEAR 
        FROM TO_DATE(PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR, 'DD/MM/YYYY')
    ) AS PUBLICATION_DATE
    FROM GCD_ISSUE
)
WHERE PUBLICATION_DATE IS NOT NULL
ORDER BY PUBLICATION_DATE ASC;

