SELECT FEATURE
FROM (
    SELECT S.FEATURE, SG.GENRE
    FROM GCD_STORY S, GCD_STORY_TO_GENRE STG, GCD_STORY_GENRE SG
    WHERE S.ID=STG.STORY_ID AND STG.GENRE_ID=SG.ID
)
WHERE GENRE IN ('humor', 'crime', 'romance')
GROUP BY FEATURE
HAVING COUNT(*) = 3;