SELECT COUNT(*) AS Count_Per_year, YEAR
FROM(
    SELECT EXTRACT(
        YEAR 
        FROM TO_DATE(PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR, 'MONTH YYYY')
    ) AS YEAR
    FROM GCD_ISSUE
)
WHERE YEAR>=1965 AND YEAR<=1975
GROUP BY YEAR
ORDER BY YEAR;